name: Add To GitHub projects

on:
  workflow_call:
   inputs:
      github-token:
        type: string
        required: true

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/orgs/TestCarina/projects/1
          github-token: ${{ inputs.github-token }}
#           labeled: bug
#           label-operator: OR
